#!/bin/bash

# Start mcvirt-agent
service mcvirt-agent stop || true

# Remove any pyc files from source
find /usr/lib/python2.7/dist-packages/mcvirt -type f -name '*.pyc' -delete || true

# Update rc, removing services
update-rc.d -f mcvirt-agent remove >/dev/null || exit $?
