#!/usr/bin/python

import sys
import atexit
sys.path.insert(0, '/usr/lib')

from mcvirt.rpc.name_server import NameServer
from mcvirt.rpc.rpc_daemon import RpcNSMixinDaemon

# Start Pyro name server
nameserver = NameServer()
nameserver.start()

# Wait for nameserver
ns = nameserver.obtainConnection()

# Create RPC Daemo and start
daemon = RpcNSMixinDaemon(name_server=ns)
daemon.registerFactories()
daemon.start()
