#!/usr/bin/python

import sys
import atexit
sys.path.insert(0, '/usr/lib')

from mcvirt.rpc.name_server import NameServer
from mcvirt.rpc.rpc_daemon import RpcNSMixinDaemon

# Start Pyro name server
nameserver = NameServer()
# Run external nameserver for now, due to connection errors.
#nameserver.start()

# Wait for nameserver
nameserver.obtainConnection()

# Create RPC Daemo and start
daemon = RpcNSMixinDaemon()
daemon.start()
