#!/bin/bash

# Start mcvirt ns and mcvirtd
service mcvirtd stop || true
service mcvirt-ns stop || true

# Remove any pyc files from source
find /usr/lib/python2.7/dist-packages/mcvirt -type f -name '*.pyc' -del || true

# Update rc, removing services
update-rc.d -f mcvirt-ns remove >/dev/null || exit $?
update-rc.d -f mcvirtd remove >/dev/null || exit $?
